### ISSUE TITLE
overlay arp table is not aligned with consul.  

### ISSUE THREAD

**Issue by odedpriva** [moby/libnetwork#2089]
Hi, 

I had an issue with connectivity between containers . 
- after investigating I found that the overlay network arp table on one server does not include entries for few containers 
- those entries exists in the cluster-store ( Consul v1.0.2 )
- restart container solved the issue and arp table was updated. 
- this is not swarm cluster. 

1. I believe this is a bug, but as a temporary workaround, is there a way to manually refresh arp table from consul ?

I have the following servers: 

- 2 application servers
- 1 consul server used as  cluster-store 

Docker version: 
```
Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

```

on the application servers here is the configuration
```
# cat /etc/docker/daemon.json
{
    "cluster-store": "consul://consul-internal.silver.eu-west-1.***.com:8500",
    "cluster-advertise": "ens3:2376",
     "debug": true
}
```

**Comment by akerouanton** [comment]
Thanks for reporting!

Swarm v1 isn't supported anymore, and this repo is now defunct (code has moved to https://github.com/moby/moby/tree/master/libnetwork), and not actively watched by maintainers. So let me close this issue.
