### ISSUE TITLE
Network driver with a specific Tx and Rx behavior

### ISSUE THREAD

**Issue by ghost** [moby/libnetwork#2090]
Hi,

How can I create a network driver with a specific Tx and Rx behavior? In particular I would like that when the container makes a request to the driver, for example Tx the driver modifies Tx in MyTx.

**Comment by akerouanton** [comment]
As of Docker v27.0, there's no way to achieve that currently, although there's a feature request opened for a long time in Moby repo: https://github.com/moby/moby/issues/4763.

This repo is now defunct, and not actively watched by maintainers, so let me close this issue.
