### ISSUE TITLE
Hard coded syscall.AF_INET breaks ipv6 operation for ipvs destination list

### ISSUE THREAD

**Issue by uablrek** [moby/libnetwork#2289]
The hard-coded value is here;
https://github.com/docker/libnetwork/blob/d7b61745d16675c9f548b19f06fda80d422a74f0/ipvs/netlink.go#L425

This breaks the ipvs sync function in Kubernetes in ipv6-only configuration with proxy-mode=ipvs as described in this issue;
https://github.com/kubernetes/kubernetes/issues/65006

**Comment by aojea** [comment]
@uablrek seems this was fixed by https://github.com/docker/libnetwork/pull/2416

**Comment by thaJeztah** [comment]
ping @selansen @euanh looks like this can be closed

**Comment by uablrek** [comment]
Problem solved a long time ago.
