### ISSUE TITLE
DOCKER-USER chain not created or enforced if default bridge is disabled

### ISSUE THREAD

**Issue by bephinix** [moby/libnetwork#2439]
### Bug Description

If you disable docker's default bride `docker0`, the `DOCKER-USER` chain is not created. If the chain already exists, its position is not enforced. You need to create a **new** bridge network (after every startup of docker) to trigger the expected behavior.

### Reason for Bug

If docker's default bridge `docker0` is enabled, docker (or moby) will calll `NewNetwork()` to creates the bridge. In `NewNetwork()` the function `arrangeUserFilterRule()` is called, which will create and enforce the `DOCKER-USER` chain in `FORWARD`.

See:
[Code 1](https://github.com/moby/moby/blob/cd1356d9ea6307659add38d6689a5b2ecb214c90/daemon/daemon_unix.go#L918)
[Code 2](https://github.com/moby/moby/blob/cd1356d9ea6307659add38d6689a5b2ecb214c90/daemon/daemon_unix.go#L1062)
[Code 3](https://github.com/docker/libnetwork/blob/09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1/controller.go#L913)

### Possible Solution

You should solve this by calling `arrangeUserFilterRule()` at the end of `setupIPChains()` in [setup_ip_tables.go](https://github.com/docker/libnetwork/blob/5b9fe1e1628d6077d1ba7a8c9a4310d09c8702ed/drivers/bridge/setup_ip_tables.go#L92).
This would be independent of the default docker bridge creation and DOCKER-USER will be created and enforced immediately after creating all other docker chains (isolation, port forwarding, etc.).

### Docker Info

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-9-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.911GiB
 Name: test
 ID: 4ECY:RYES:7MHM:ZAFK:RSNN:C4JA:SQDO:PWWE:OTFD:TBXX:5O65:RINR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by akerouanton** [comment]
Thanks for reporting!

We're also tracking this issue in https://github.com/moby/moby/issues/48560. Hopefully this will be fixed in v28.0 (or maybe a minor / patch release of v27).

Since this repo is now defunct (code was moved to https://github.com/moby/moby/tree/master/libnetwork), and not actively watched by maintainers, let me close this issue.
