### ISSUE TITLE
IPv4 address parse error

### ISSUE THREAD

**Issue by ep4eg** [moby/libnetwork#2480]
For a long time, I've been using vendored ipvs package, recently I updated it to the latest version and it doesn't work anymore since address family is determined incorrectly. I don't have any IPv6 addresses.

Here's output of `GetDestinations()`
`parseIP Error ip=[10 1 1 21 0 0 0 0 0 0 0 0 0 0 0 0]`

**Comment by kwanhur** [comment]
root cause no destination address family return by IPVS, see PR #2487
