### ISSUE TITLE
Update docs to clarify that the repo has moved to moby/moby/libnetwork

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/libnetwork#2641]
The repo has moved to https://github.com/moby/moby/tree/master/libnetwork for Docker/Moby 21.XX (https://github.com/moby/moby/pull/42262) .

TBD: where to maintain 20.10 branch.

**Comment by akerouanton** [comment]
Fixed by https://github.com/moby/libnetwork/pull/2665.
